# Generated by Django 5.0.6 on 2024-05-24 04:07

import app.models
import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='이름', max_length=20)),
                ('description', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='이름', max_length=20)),
                ('category', django_choices_field.fields.TextChoicesField(choices=[('citrus', 'Citrus'), ('berry', 'Berry')], choices_enum=app.models.FruitCategory, help_text='종류', max_length=6)),
                ('color', models.ForeignKey(blank=True, help_text='색상', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='app.color')),
            ],
        ),
    ]
