# Generated by Django 5.0.6 on 2024-05-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='wiki_urls',
            field=models.SlugField(blank=True, help_text='Wiki URLs'),
        ),
    ]
