# Generated by Django 5.0.6 on 2024-05-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fruit_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='create_time',
            new_name='created_at',
        ),
    ]
