# Generated by Django 5.0.6 on 2024-05-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_create_time_fruit_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='변경 일자'),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='생성 일자'),
        ),
    ]
