# Generated by Django 5.0.6 on 2024-05-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_history_output'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
